### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by drago87** [TFC-Metallum/TFCTech#54] opened 2020-04-29 13:51 UTC
[Crash report](https://paste.dimdev.org/urexusijuq.mccrash)
could be dublicate of [issue 48](https://github.com/TFC-Metallum/TFCTech/issues/48)

**Comment by aliceingame** [comment] 2020-04-30 15:26
I think duplicate of #52 and not 48.
Yes, both are most likely caused by something changing in TFC, but probably no the same thing.

**Closed** 2020-05-03 15:15 UTC
Labels: duplicate
