### ISSUE TITLE
Glass does not melt in smeltery.

### ISSUE THREAD

**Issue by DanDragon401** [TFC-Metallum/TFCTech#62] opened 2020-07-26 00:09 UTC
I tried melting glass in the smeltery from this mod but it didn't work.

**Comment by DisasterMoo** [comment] 2020-07-31 16:42
Need more info to find the cause. Can you describe (if possible with screenshots) how are you trying to melt glass? Also, which Forge, TFC, TFCTech and other mods (relevant ones that may interfere) are you using?

**Comment by DisasterMoo** [comment] 2020-09-22 16:01
Since no more updates on this, and looking at how #69 mentioned he used crafttweaker to change TFC's glass shards to TFCTech's Smeltery, I assume the structure is working, so closing.

**Closed by DisasterMoo** 2020-09-22 16:01 UTC
Labels: unconfirmed bug
